<?php
/** @var \AHT\AHTtest\Block\Template $block */
?>

<div class="template">
    <h1 style="text-align: center;">Add</h1>
    <form action="<?=$block->getBaseUrl()?>haha/index/save" method="post">
        <input type="text" name="name" placeholder="Enter name ...." style="width:500px ; margin-bottom:30px;">
        <input type="text" name="age" placeholder=" Enter age ...."style="width:500px ; margin-bottom:30px;">
        <button type="submit">Submit</button>
   </form>
</div>